MERGE INTO WATCHER USING (VALUES('REGIONAL PARTNER A', 'SOURCE_PARTNER_A', 'DEST_PARTNER_A', '/home/biobroker/DIR_A', '5000', 'ALWAYS_MATCH')) 
	AS V(NAME, SOURCE_ENDPOINT_NAME, DESTINATION_ENDPOINT_NAME, PATH, INTERVAL, MODE) 
	ON WATCHER.NAME = V.NAME 
	WHEN NOT MATCHED THEN INSERT (NAME, SOURCE_ENDPOINT_NAME, DESTINATION_ENDPOINT_NAME, PATH, INTERVAL, MODE) VALUES V.NAME, V.SOURCE_ENDPOINT_NAME, V.DESTINATION_ENDPOINT_NAME, V.PATH, V.INTERVAL, V.MODE;

MERGE INTO WATCHER USING (VALUES('REGIONAL PARTNER B', 'SOURCE_PARTNER_B', 'DEST_PARTNER_B', '/home/biobroker/DIR_B', '5000', 'ALWAYS_NOMATCH')) 
	AS V(NAME, SOURCE_ENDPOINT_NAME, DESTINATION_ENDPOINT_NAME, PATH, INTERVAL, MODE) 
	ON WATCHER.NAME = V.NAME 
	WHEN NOT MATCHED THEN INSERT (NAME, SOURCE_ENDPOINT_NAME, DESTINATION_ENDPOINT_NAME, PATH, INTERVAL, MODE) VALUES V.NAME, V.SOURCE_ENDPOINT_NAME, V.DESTINATION_ENDPOINT_NAME, V.PATH, V.INTERVAL, V.MODE;
